### ISSUE TITLE
Won't build with the latest Nightly

### ISSUE THREAD

**Issue by Yoric** [dropbox/rust-brotli#19] opened 2018-05-18 21:29 UTC
I get a bunch of errors such as:

`^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize``

See for instance https://travis-ci.org/binast/binjs-ref/jobs/380663418#L725 .

**Comment by Yoric** [comment] 2018-05-18 21:35
Ah, I see that it's already being fixed. Thanks :)

**Comment by dekellum** [comment] 2018-05-21 18:06
Not fixed as of:

rustc 1.28.0-nightly (a1d4a9503 2018-05-20)

Example failure:

https://travis-ci.org/dekellum/body-image/jobs/380453803#L299

**Comment by dekellum** [comment] 2018-05-22 20:53
The issue is also tracked for rustc, with other effected crates, in rust-lang/rust#50825.

Above I was seeing this issue with brotli 1.2.0, but an upgrade (dekellum/body-image@2741bbc4) to brotli 2.2.1 (released May 20) fixes the issue for me, presumably because of ae6d9d2d.  

Some brief release notes or at least release tags for the brotli crate, could help users to help themselves for bugs like this. I'm also wondering what else has changed in the major 2.x release series.

**Comment by danielrh** [comment] 2018-06-05 00:47
This is fixed in 2.3 which also contains a fix for flush()

**Closed by danielrh** 2018-06-05 00:47 UTC
